name: blog

channels:
  - conda-forge
  - pytorch

dependencies:
  # Python
  - python=3.6
  - ipython
  - pip

  # Science
  - numpy
  - scipy

  # ML/DL
  - scikit-learn
  - pytorch=1.3
  - torchvision
  
  # Misc
  - folium

  # Jupyter
  - jupyter
  - nbstripout
  - nbconvert
